Create Database AnalytixLabs ;
Use AnalytixLabs ; 



--    DATA PREP & UNDERSTANDING ---------------------------------------------------------------------------------------

Select count(*)CNT from customer ; -- Q1.) Count of No. of rows 
Select count(*)CONT from prod_cat_info ; 
Select count(*)CN_T from transactions ; 
select count(transaction_id) from transactions where total_amt > 0 ; -- Q2.) Trans that have a return

select year(tran_date) YR , Month(tran_date) MNT , DAY(tran_date)DTE from transactions limit 10 ; -- Q4.) 
select * from prod_cat_info where prod_subcat = "DIY" ; -- Q5.) which prod cat does sub cat DIY belong to ? 


--    DATA ANALYSIS ---------------------------------------------------------------------------------------------------

								--  Q1.) Which channel is most frequently used 
                                --  ANS) e-Shop - 9311
                                
                                
select store_type , Count(*) from transactions
group by store_type 
order by 2 desc ; 

								-- Q2.) count of male and female customer 
                                
Select Gender , count(*) from customer group by gender order by 1 ;


								-- Q3.) which city has max cust and how many . 
                                --  ANS) - City 3-595
                                
                                
select city_code as CITY , Count(*)CNT from customer
group by city_code order by 2 desc ; 


								-- Q4.) sub cat where cat is Books 
                                
                                
select prod_subcat from prod_cat_info where prod_cat="Books";


								-- Q5 Max qnt of prod ordered
                                
									
select  a.Qty, b.prod_cat  from  transactions a
inner join prod_cat_info b on a.prod_cat_code = b.prod_cat_code
order by a.Qty desc limit 1;


								-- Q6) total revenue gen in category Electronics and Books 
                                
                                
 select a.prod_cat,  SUM(b.total_amt)REVENUE_GENERATED
 from prod_cat_info a
 inner Join transactions b on  a.prod_cat_code = b.prod_cat_code
 where a.prod_cat = "Electronics" or a.prod_cat = "Books" 
 group by a.prod_cat;
 
 
 
								-- Q7.) >10 Transct excl returns - customers
                                
                                

select count(*)CNT from 
(Select cust_id , count(transaction_id) from transactions 
where total_amt > 0
group by cust_id 
having count(transaction_id) > 10)xyz ;



								-- Q8.) Combined revenue earned from Elec and clothing categ , from "flagships stores"
                                
                                
							

select  SUM(b.total_amt)REVENUE_GENERATED
from prod_cat_info a
inner Join transactions b 
on  a.prod_cat_code = b.prod_cat_code AND  a.prod_sub_cat_code = b.prod_subcat_code
where a.prod_cat In ("Electronics" ,"Books") AND b.store_type in ("Flagship store ") ;



								-- Q9.) toal rev gen from 'Male' cust in ' Elect' categ. Display total revenue by prod sub cat 
                                
                                
                                
select SUM(a.total_amt)Revenue, b.Gender, c.prod_subcat  from  transactions a
join customer b on a.cust_id = b.customer_Id 
join prod_cat_info c on  c.prod_cat_code = a.prod_cat_code  AND  c.prod_sub_cat_code = a.prod_subcat_code
where b.gender = 'M' AND  c.prod_cat = 'Electronics'
group by  b.Gender, c.prod_subcat ;  



				-- Q10.) what is % of sales and retures by prod sub cat;Display only top 5 sub cat in terms of sale 
                        

with xyz as ( 
select b.prod_subcat  , 
SUM(case when Total_amt > 0 then total_amt end ) as Sales ,
SUM(case when total_amt < 0 then total_amt * -1 end ) as return_s
from transactions a
join prod_cat_info b on a.prod_cat_code = b.prod_cat_code and a.prod_subcat_code = b.prod_sub_cat_code 
group by b.prod_subcat )

select prod_subcat , Sales/(select SUM(sales) from xyz)  * 100 as PRCNTG_SALE , 
return_s / ( select SUM(return_s) from xyz ) * 100 as PRCNTG_RETURN
from xyz 
group by prod_subcat 
order by Sales desc limit 5 ;




                        
/* 11 .) For all customers aged - 25 to 35 years, what is the total revenue generated by these consumers in last 30 days of transactions
							from max transaction date available in the data? */
  
    
-- Select MAX(Str_to_date(tran_date,'%d-%m-%Y' )) from transactions  - To see Max Trans date
  
SELECT cust_id , SUM(total_amt) as revenue
FROM transactions 
WHERE 
Cust_ID IN (
Select customer_id from customer 
where  Timestampdiff(year,str_to_date(DOB,'%d-%m-%Y' ), curdate()) Between 25 AND 35) 
AND  Str_to_date(tran_date,'%d-%m-%Y' ) < '2014-02-28' 
AND  Str_to_date(tran_date,'%d-%m-%Y' ) > '2014-01-28'
group by Cust_id ;


                       
--            12.) Which prod cat has seen the max value of return in last 3 months of trans                        
                   
 
 with xyz as (
select  tran_date , prod_cat , 
 SUM(case when total_amt < 0 then total_amt * -1 end ) as Return_s 
 from transactions a 
 join prod_cat_info b on a.prod_cat_code = b.prod_cat_code 
 group by  tran_date,prod_cat 
 order by Return_s desc  
 )
 Select prod_cat , MAX(Return_s) from xyz 
 where Str_to_date(tran_date,'%d-%m-%Y') < '2014-02-28' 
 AND Str_to_date(tran_date,'%d-%m-%Y') >= '2013-11-28' 
 Group by prod_cat limit 1 ;


											
			-- Q.13)Which store-type sells the maximum products; by value of sales amount and by quantity sold? output  : 
                 
                 
                 
select Store_type , SUM(total_amt) , SUM(QTY)
from transactions 
group by Store_type
HAVING SUM(total_amt) >= ( select MAX(total_amt) from transactions ) AND
 SUM(QTY) >= ( select MAX(QTY) from transactions ) limit 1 ;



						-- Q.14) categories where Avg rev is above overall average 
                        
                        
select a.prod_cat , AVG(b.total_amt) 
from prod_cat_info a 
join transactions b on a.prod_cat_code = b.prod_cat_code AND b.prod_subcat_code = a.prod_sub_cat_code 
group by a.prod_cat 
having AVG(b.total_amt) >= (select AVG(total_amt) from transactions )   ;
                      
                        

						-- Q.15) Avg and total rev by each sub cat for CATegories wich are top 5 in QTY sold 


select  prod_cat , prod_subcat ,  AVG(total_amt), SUM(total_amt)
from transactions a 
join prod_cat_info b on a.prod_cat_code =  b.prod_cat_code  AND a.prod_subcat_code = b.prod_sub_cat_code 
where  prod_cat IN 
(select prod_cat from 
( select prod_cat, SUM(QTY) AS Total_sum
from transactions a 
join prod_cat_info b on a.prod_cat_code =  b.prod_cat_code  AND a.prod_subcat_code = b.prod_sub_cat_code 
 group by prod_cat  order by SUM(Qty) desc limit 5)xyz)
group by  prod_cat , prod_subcat  ;



-- x -------------- x ---------------- x ------------ x ------------ x ------------- x ------------- x --------------- x ------- x --






